---
spring:
  config.activate.on-profile: default

server:
  port: 8082
cds:
  datasource:
    auto-config.enabled: false
    
  messaging.services:
    - name: "messaging"
      kind: "enterprise-messaging"

